# Site settings
title: Fredrik Johansson
description:
  This is the portfolio of Fredrik Johansson. It includes some of my work
  as an Interaction Designer, UI/UX designer and Software Developer.
baseurl: ""

# Build settings
markdown: kramdown
exclude: [
        "/assets/images-fullsize",
        "CNAME"
      ]
gems:
  - jekyll-sitemap

# Minify settings
sass:
  style: compressed

compress_html:
  comments: ["<!--", "-->"]
  clippings: all

collections:
  work:
    output: true

front_page_show_case: [arcreader.md, chatserver.md, symbolismvstext.md]

navigation:
    - text: Home
      url: /
    - text: Work
      url: /work/
    - text: Project Lemon
      url: /projectlemon/
    - text: About Me
      url: /about/